registry:
  restart: always
  image: registry:2
  container_name: registry
  environment:
    REGISTRY_STORAGE_DELETE_ENABLED: "true"
  ports:
    - 5000:5000
  volumes:
    - /var/lib/docker-registry:/var/lib/registry
