apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs1-pv0003
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Mi
  volumeName: pv0003
