apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0003
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
#  persistentVolumeReclaimPolicy: Recycle
#  storageClassName: slow
#  mountOptions:
#    - hard
#    - nfsvers=4.1
  nfs:
    path: /
    server: 192.168.122.1
