apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: nginx
    name: test-container
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
    resources:
      requests:
        cpu: "100m"
        memory: "10Mi" 
      limits:
        cpu: "200m"
        memory: "20Mi" 
  volumes:
  - name: cache-volume
    emptyDir: {}
