apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/config.hash: bf901a0b149089706e3a505c6d1811be
    kubernetes.io/config.mirror: bf901a0b149089706e3a505c6d1811be
    kubernetes.io/config.seen: 2017-07-11T13:26:33.717821338Z
    kubernetes.io/config.source: file
  creationTimestamp: 2017-07-11T13:26:33Z
  labels:
    k8s-app: kube-controller
  name: kube-controller-manager-k8s0
  namespace: kube-system
  resourceVersion: "11229829"
  selfLink: /api/v1/namespaces/kube-system/pods/kube-controller-manager-k8s0
  uid: 8ec18172-663c-11e7-bb5f-525400570e7e
spec:
  containers:
  - command:
    - /hyperkube
    - controller-manager
    - --master=http://127.0.0.1:8080
    - --leader-elect=true
    - --service-account-private-key-file=/etc/kubernetes/ssl/apiserver-key.pem
    - --root-ca-file=/etc/kubernetes/ssl/ca.pem
    - --cluster-signing-cert-file=/etc/kubernetes/ssl/ca.pem
    - --cluster-signing-key-file=/etc/kubernetes/ssl/ca-key.pem
    - --enable-hostpath-provisioner=false
    - --node-monitor-grace-period=40s
    - --node-monitor-period=5s
    - --pod-eviction-timeout=5m0s
    - --v=2
    image: quay.io/coreos/hyperkube:v1.6.4_coreos.0
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10252
        scheme: HTTP
      initialDelaySeconds: 30
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 10
    name: kube-controller-manager
    resources:
      limits:
        cpu: 250m
        memory: 512M
      requests:
        cpu: 100m
        memory: 100M
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/kubernetes/ssl
      name: ssl-certs-kubernetes
      readOnly: true
  dnsPolicy: ClusterFirst
  hostNetwork: true
  nodeName: k8s0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    operator: Exists
  volumes:
  - hostPath:
      path: /etc/kubernetes/ssl
    name: ssl-certs-kubernetes
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2017-10-18T13:20:28Z
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: 2017-10-18T13:20:30Z
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: 2017-10-18T13:20:28Z
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://d2cb71f885511d2373e30e89e7c5d2689cc9ad9a4c2d3e55e7f2260dcfbfdf72
    image: quay.io/coreos/hyperkube:v1.6.4_coreos.0
    imageID: docker-pullable://quay.io/coreos/hyperkube@sha256:297f45919160ea076831cd067833ad3b64c789fcb3491016822e6f867d16dcd5
    lastState:
      terminated:
        containerID: docker://ab8bf4e2cb1fe96d94db328137e30836ed324438ca6aab7552ec0f444e82f510
        exitCode: 255
        finishedAt: 2017-10-18T13:20:20Z
        reason: Error
        startedAt: 2017-10-18T02:43:19Z
    name: kube-controller-manager
    ready: true
    restartCount: 5
    state:
      running:
        startedAt: 2017-10-18T13:20:29Z
  hostIP: 192.168.122.24
  phase: Running
  podIP: 192.168.122.24
  qosClass: Burstable
  startTime: 2017-10-18T13:20:28Z
