apiVersion: v1
kind: Pod
metadata:
   name: test-configmap
spec:
  containers:
    - name: test-configmap
      image: busybox
      command: ["bin/sh", "-c","env"] 
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      env:
        - name: LEVEL_KEY
          valueFrom: 
            configMapKeyRef:
              name: special-config
              key: special.how
        - name: TYPE_KEY
          valueFrom: 
            configMapKeyRef:
              name: special-config
              key: special.type
      envFrom:
        - configMapRef:
            name: env-config
  restartPolicy: Never


